name: Docker Subir al Servidor de Docker Hub

on:
  push:
    branches:
      - Prueba1
  workflow_dispatch:


jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_SECRET }}" | docker login -u "lostyrl7" --password-stdin

      - name: Construir la imagen Docker
        run: docker build -t mi-hello-world:latest .

      - name: Etiquetar la imagen para Docker Hub
        run: docker tag mi-hello-world:latest lostyrl7/mi-hello-world:latest

      - name: Subir imagen a Docker Hub
        run: docker push lostyrl7/mi-hello-world:latest

